// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Dvu(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
  input         clock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
                reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
  output        io_req_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  input         io_req_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  input  [4:0]  io_req_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  input  [1:0]  io_req_bits_op,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  input         io_rs1_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  input  [31:0] io_rs1_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  input         io_rs2_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  input  [31:0] io_rs2_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  input         io_rd_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  output        io_rd_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  output [4:0]  io_rd_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
  output [31:0] io_rd_bits_data	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:40:14
);

  reg         active;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:71:23
  reg         compute;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:72:24
  reg  [4:0]  addr1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:74:25
  reg         signed1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:75:25
  reg         divide1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:76:25
  reg  [4:0]  addr2;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:77:25
  reg         signed2d;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:78:25
  reg         signed2r;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:79:25
  reg         divide2;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:80:25
  reg  [5:0]  count;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:82:23
  reg  [31:0] divide;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:84:23
  reg  [31:0] remain;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:85:23
  reg  [31:0] denom;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:86:23
  wire        io_req_ready_0 = ~active & ~compute & ~(count[5]);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:71:23, :72:24, :82:23, :90:{19,27,30,39,42,48}
  always @(posedge clock) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
    if (reset) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
      active <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:71:23
      compute <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:72:24
      addr1 <= 5'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:74:25
      signed1 <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:75:25
      divide1 <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:76:25
      addr2 <= 5'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:77:25
      signed2d <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:78:25
      signed2r <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:79:25
      divide2 <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:80:25
      count <= 6'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:82:23
      divide <= 32'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:84:23
      remain <= 32'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:85:23
      denom <= 32'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:86:23
    end
    else begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
      automatic logic _divide1_T = io_req_valid & io_req_ready_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:90:{27,39}, :99:22
      active <= _divide1_T | count != 6'h1E & active;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:71:23, :82:23, :99:{22,39}, :100:12, :101:{22,32}, :102:12
      compute <= active;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:71:23, :72:24
      if (_divide1_T) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:99:22
        automatic logic _divide1_T_1 = io_req_bits_op == 2'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :110:42
        addr1 <= io_req_bits_addr;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:74:25
        signed1 <= |{io_req_bits_op == 2'h2, _divide1_T_1};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :75:25, :110:42
        divide1 <= |{io_req_bits_op == 2'h1, _divide1_T_1};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :76:25, :110:42, :112:42
      end
      if (active & ~compute) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:71:23, :72:24, :90:30, :114:16
        automatic logic [31:0] inp;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:120:18
        automatic logic [15:0] _clz_T_12;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        automatic logic [15:0] _clz_T_22;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        automatic logic [15:0] _clz_T_32;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        automatic logic [14:0] _clz_T_42;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        automatic logic [7:0]  _clz_T_53;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        automatic logic [7:0]  _clz_T_63;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        automatic logic [7:0]  _clz_T_73;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        automatic logic [4:0]  clz;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:8, :124:18, src/main/scala/chisel3/util/Mux.scala:58:84
        automatic logic [62:0] _divide_T;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:127:19
        inp = signed1 & io_rs1_data[31] ? ~io_rs1_data + 32'h1 : io_rs1_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:75:25, :116:40, :120:{18,27,47,60}
        _clz_T_12 = {8'h0, inp[15:8]} | {inp[7:0], 8'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:{48,53}, :120:18
        _clz_T_22 = {4'h0, _clz_T_12[15:4] & 12'hF0F} | {_clz_T_12[11:0] & 12'hF0F, 4'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        _clz_T_32 =
          {2'h0, _clz_T_22[15:2] & 14'h3333} | {_clz_T_22[13:0] & 14'h3333, 2'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :95:48
        _clz_T_42 = _clz_T_32[15:1] & 15'h5555 | {1'h0, _clz_T_32[12:0] & 13'h1555, 1'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        _clz_T_53 = {4'h0, inp[23:20]} | {inp[19:16], 4'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:{48,53}, :120:18
        _clz_T_63 = {2'h0, _clz_T_53[7:2] & 6'h33} | {_clz_T_53[5:0] & 6'h33, 2'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :95:48
        _clz_T_73 = {1'h0, _clz_T_63[7:1] & 7'h55} | {_clz_T_63[6:0] & 7'h55, 1'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:48
        clz =
          ~(|io_rs2_data) | inp[31] | inp[30]
            ? 5'h0
            : inp[29]
                ? 5'h1
                : inp[28]
                    ? 5'h2
                    : inp[27]
                        ? 5'h3
                        : inp[26]
                            ? 5'h4
                            : inp[25]
                                ? 5'h5
                                : inp[24]
                                    ? 5'h6
                                    : _clz_T_73[0]
                                        ? 5'h7
                                        : _clz_T_73[1]
                                            ? 5'h8
                                            : _clz_T_73[2]
                                                ? 5'h9
                                                : _clz_T_73[3]
                                                    ? 5'hA
                                                    : _clz_T_73[4]
                                                        ? 5'hB
                                                        : _clz_T_73[5]
                                                            ? 5'hC
                                                            : _clz_T_73[6]
                                                                ? 5'hD
                                                                : _clz_T_73[7]
                                                                    ? 5'hE
                                                                    : _clz_T_42[0]
                                                                        ? 5'hF
                                                                        : _clz_T_42[1]
                                                                            ? 5'h10
                                                                            : _clz_T_42[2]
                                                                                ? 5'h11
                                                                                : _clz_T_42[3]
                                                                                    ? 5'h12
                                                                                    : _clz_T_42[4]
                                                                                        ? 5'h13
                                                                                        : _clz_T_42[5]
                                                                                            ? 5'h14
                                                                                            : _clz_T_42[6]
                                                                                                ? 5'h15
                                                                                                : _clz_T_42[7]
                                                                                                    ? 5'h16
                                                                                                    : _clz_T_42[8]
                                                                                                        ? 5'h17
                                                                                                        : _clz_T_42[9]
                                                                                                            ? 5'h18
                                                                                                            : _clz_T_42[10]
                                                                                                                ? 5'h19
                                                                                                                : _clz_T_42[11]
                                                                                                                    ? 5'h1A
                                                                                                                    : _clz_T_42[12]
                                                                                                                        ? 5'h1B
                                                                                                                        : _clz_T_42[13]
                                                                                                                            ? 5'h1C
                                                                                                                            : _clz_T_42[14]
                                                                                                                                ? 5'h1D
                                                                                                                                : 5'h1E;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:88:31, :95:{8,13,48,53}, :120:18, :124:18, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:48:45
        addr2 <= addr1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:74:25, :77:25
        signed2d <= signed1 & io_rs1_data[31] != io_rs2_data[31] & (|io_rs2_data);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:75:25, :78:25, :88:31, :116:{25,40,45,60,66}
        signed2r <= signed1 & io_rs1_data[31];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:75:25, :79:25, :116:40, :117:25
        divide2 <= divide1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:76:25, :80:25
        count <= {1'h0, clz};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:82:23, :95:8, :124:18, :129:12, src/main/scala/chisel3/util/Mux.scala:58:84
        _divide_T = {31'h0, inp} << clz;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:95:8, :120:18, :124:18, :127:19, src/main/scala/chisel3/util/Mux.scala:58:84
        divide <= _divide_T[31:0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:84:23, :127:{12,19}
        remain <= 32'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:85:23
        denom <= signed1 & io_rs2_data[31] ? ~io_rs2_data + 32'h1 : io_rs2_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:75:25, :86:23, :116:60, :126:{18,27,47,60}
      end
      else if (compute & ~(count[5])) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:72:24, :82:23, :130:{24,33}
        automatic logic [32:0] subtract;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:55:30
        subtract = {1'h0, remain[30:0], divide[31]} - {1'h0, denom};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:54:{34,51}, :55:30, :84:23, :85:23, :86:23
        count <= count + 6'h1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:82:23, :134:20
        divide <= subtract[32] ? {divide[30:0], 1'h0} : {divide[30:0], 1'h1};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:55:30, :60:{20,26}, :61:{17,23,33}, :64:{17,23,33}, :84:23
        remain <= subtract[32] ? {remain[30:0], divide[31]} : subtract[31:0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:54:{24,34,51}, :55:30, :60:{20,26}, :62:{17,28}, :65:17, :84:23, :85:23
      end
      else if (count[5] & io_rd_ready)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:82:23, :90:48, :135:28
        count <= 6'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:82:23
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
      `FIRRTL_BEFORE_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
      automatic logic [31:0] _RANDOM[0:3];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
      `ifdef INIT_RANDOM_PROLOG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
        `INIT_RANDOM_PROLOG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
        end	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
        active = _RANDOM[2'h0][0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23
        compute = _RANDOM[2'h0][1];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :72:24
        addr1 = _RANDOM[2'h0][6:2];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :74:25
        signed1 = _RANDOM[2'h0][7];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :75:25
        divide1 = _RANDOM[2'h0][8];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :76:25
        addr2 = _RANDOM[2'h0][13:9];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :77:25
        signed2d = _RANDOM[2'h0][14];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :78:25
        signed2r = _RANDOM[2'h0][15];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :79:25
        divide2 = _RANDOM[2'h0][16];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :80:25
        count = _RANDOM[2'h0][22:17];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :82:23
        divide = {_RANDOM[2'h0][31:23], _RANDOM[2'h1][22:0]};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :71:23, :84:23
        remain = {_RANDOM[2'h1][31:23], _RANDOM[2'h2][22:0]};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :84:23, :85:23
        denom = {_RANDOM[2'h2][31:23], _RANDOM[2'h3][22:0]};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :85:23, :86:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
      `FIRRTL_AFTER_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = io_req_ready_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :90:{27,39}
  assign io_rd_valid = count[5];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :82:23, :90:48
  assign io_rd_bits_addr = addr2;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :77:25
  assign io_rd_bits_data =
    divide2 ? (signed2d ? ~divide + 32'h1 : divide) : signed2r ? ~remain + 32'h1 : remain;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Dvu.scala:39:7, :78:25, :79:25, :80:25, :84:23, :85:23, :139:{16,27,35}, :140:{16,27,35}, :144:25
endmodule

