// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module Arbiter4_MluCmd(	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  output       io_in_0_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input        io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [4:0] io_in_0_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [2:0] io_in_0_bits_op,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output       io_in_1_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input        io_in_1_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [4:0] io_in_1_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [2:0] io_in_1_bits_op,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output       io_in_2_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input        io_in_2_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [4:0] io_in_2_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [2:0] io_in_2_bits_op,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output       io_in_3_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input        io_in_3_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [4:0] io_in_3_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [2:0] io_in_3_bits_op,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input        io_out_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output       io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [4:0] io_out_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [2:0] io_out_bits_op,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [1:0] io_chosen	// src/main/scala/chisel3/util/Arbiter.scala:156:14
);

  wire _grant_T = io_in_0_valid | io_in_1_valid;	// src/main/scala/chisel3/util/Arbiter.scala:45:68
  wire _io_out_valid_T = _grant_T | io_in_2_valid;	// src/main/scala/chisel3/util/Arbiter.scala:45:68
  assign io_in_0_ready = io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:45:78, :149:7, :169:19
  assign io_in_2_ready = ~_grant_T & io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:45:{68,78}, :149:7, :169:19
  assign io_in_3_ready = ~_io_out_valid_T & io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:45:{68,78}, :149:7, :169:19
  assign io_out_valid = _io_out_valid_T | io_in_3_valid;	// src/main/scala/chisel3/util/Arbiter.scala:45:68, :149:7, :170:31
  assign io_out_bits_addr =
    io_in_0_valid
      ? io_in_0_bits_addr
      : io_in_1_valid
          ? io_in_1_bits_addr
          : io_in_2_valid ? io_in_2_bits_addr : io_in_3_bits_addr;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19
  assign io_out_bits_op =
    io_in_0_valid
      ? io_in_0_bits_op
      : io_in_1_valid
          ? io_in_1_bits_op
          : io_in_2_valid ? io_in_2_bits_op : io_in_3_bits_op;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19
  assign io_chosen = io_in_0_valid ? 2'h0 : io_in_1_valid ? 2'h1 : {1'h1, ~io_in_2_valid};	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :158:13, :161:26, :162:17
endmodule


// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue1_MluStage1(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input        clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
               reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output       io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input        io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0] io_enq_bits_rd,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [2:0] io_enq_bits_op,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [3:0] io_enq_bits_sel,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input        io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output       io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0] io_deq_bits_rd,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [2:0] io_deq_bits_op,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [3:0] io_deq_bits_sel	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  reg  [11:0] ram;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg         full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire        io_enq_ready_0 = io_deq_ready | ~full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :103:{16,19}, :123:{24,39}
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    automatic logic do_enq;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    do_enq = io_enq_ready_0 & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:103:16, :123:{24,39}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (reset)	// src/main/scala/chisel3/util/Queue.scala:60:7
      full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    else if (~(do_enq == (io_deq_ready & full)))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      ram <= {io_enq_bits_rd, io_enq_bits_op, io_enq_bits_sel};	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        full = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
        ram = _RANDOM[/*Zero width*/ 1'b0][12:1];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = io_enq_ready_0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :103:16, :123:{24,39}
  assign io_deq_valid = full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
  assign io_deq_bits_rd = ram[11:7];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_op = ram[6:4];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_sel = ram[3:0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
endmodule

module Queue1_MluStage2(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input         clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output        io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0]  io_enq_bits_rd,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [2:0]  io_enq_bits_op,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [65:0] io_enq_bits_prod,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output        io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0]  io_deq_bits_rd,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [2:0]  io_deq_bits_op,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [65:0] io_deq_bits_prod	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  reg  [73:0] ram;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg         full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire        io_enq_ready_0 = io_deq_ready | ~full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :103:{16,19}, :123:{24,39}
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    automatic logic do_enq;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    do_enq = io_enq_ready_0 & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:103:16, :123:{24,39}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (reset)	// src/main/scala/chisel3/util/Queue.scala:60:7
      full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:76:27
    else if (~(do_enq == (io_deq_ready & full)))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      ram <= {io_enq_bits_rd, io_enq_bits_op, io_enq_bits_prod};	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        end	// src/main/scala/chisel3/util/Queue.scala:60:7
        full = _RANDOM[2'h0][0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
        ram = {_RANDOM[2'h0][31:1], _RANDOM[2'h1], _RANDOM[2'h2][10:0]};	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = io_enq_ready_0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :103:16, :123:{24,39}
  assign io_deq_valid = full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
  assign io_deq_bits_rd = ram[73:69];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_op = ram[68:66];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_prod = ram[65:0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
endmodule

module Mlu(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:55:7
  input         clock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:55:7
                reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:55:7
  output        io_req_0_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_req_0_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [4:0]  io_req_0_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [2:0]  io_req_0_bits_op,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  output        io_req_1_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_req_1_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [4:0]  io_req_1_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [2:0]  io_req_1_bits_op,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  output        io_req_2_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_req_2_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [4:0]  io_req_2_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [2:0]  io_req_2_bits_op,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  output        io_req_3_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_req_3_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [4:0]  io_req_3_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [2:0]  io_req_3_bits_op,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rs1_0_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [31:0] io_rs1_0_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rs1_1_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [31:0] io_rs1_1_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rs1_2_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [31:0] io_rs1_2_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rs1_3_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [31:0] io_rs1_3_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rs2_0_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [31:0] io_rs2_0_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rs2_1_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [31:0] io_rs2_1_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rs2_2_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [31:0] io_rs2_2_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rs2_3_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input  [31:0] io_rs2_3_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  input         io_rd_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  output        io_rd_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  output [4:0]  io_rd_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
  output [31:0] io_rd_bits_data	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:56:14
);

  wire        _stage3Input_q_io_enq_ready;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [2:0]  _stage3Input_q_io_deq_bits_op;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [65:0] _stage3Input_q_io_deq_bits_prod;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire        _stage2Input_q_io_enq_ready;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire        _stage2Input_q_io_deq_valid;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [4:0]  _stage2Input_q_io_deq_bits_rd;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [2:0]  _stage2Input_q_io_deq_bits_op;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [3:0]  _stage2Input_q_io_deq_bits_sel;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire        _arb_io_out_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
  wire [4:0]  _arb_io_out_bits_addr;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
  wire [2:0]  _arb_io_out_bits_op;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
  wire [1:0]  _arb_io_chosen;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
  wire [31:0] rs1 =
    (_stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel[0]
       ? io_rs1_0_data
       : 32'h0)
    | (_stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel[1]
         ? io_rs1_1_data
         : 32'h0)
    | (_stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel[2]
         ? io_rs1_2_data
         : 32'h0)
    | (_stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel[3]
         ? io_rs1_3_data
         : 32'h0);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/Library.scala:22:8, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:84:{66,74,105}, src/main/scala/chisel3/util/Queue.scala:200:21
  wire [31:0] rs2 =
    (_stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel[0]
       ? io_rs2_0_data
       : 32'h0)
    | (_stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel[1]
         ? io_rs2_1_data
         : 32'h0)
    | (_stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel[2]
         ? io_rs2_2_data
         : 32'h0)
    | (_stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel[3]
         ? io_rs2_3_data
         : 32'h0);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/Library.scala:22:8, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:84:74, :85:{66,105}, src/main/scala/chisel3/util/Queue.scala:200:21
  wire        rs2signed = _stage2Input_q_io_deq_bits_op == 3'h1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:87:32, src/main/scala/chisel3/util/Queue.scala:200:21
  Arbiter4_MluCmd arb (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
    .io_in_0_ready     (io_req_0_ready),
    .io_in_0_valid     (io_req_0_valid),
    .io_in_0_bits_addr (io_req_0_bits_addr),
    .io_in_0_bits_op   (io_req_0_bits_op),
    .io_in_1_ready     (io_req_1_ready),
    .io_in_1_valid     (io_req_1_valid),
    .io_in_1_bits_addr (io_req_1_bits_addr),
    .io_in_1_bits_op   (io_req_1_bits_op),
    .io_in_2_ready     (io_req_2_ready),
    .io_in_2_valid     (io_req_2_valid),
    .io_in_2_bits_addr (io_req_2_bits_addr),
    .io_in_2_bits_op   (io_req_2_bits_op),
    .io_in_3_ready     (io_req_3_ready),
    .io_in_3_valid     (io_req_3_valid),
    .io_in_3_bits_addr (io_req_3_bits_addr),
    .io_in_3_bits_op   (io_req_3_bits_op),
    .io_out_ready      (_stage2Input_q_io_enq_ready),	// src/main/scala/chisel3/util/Queue.scala:200:21
    .io_out_valid      (_arb_io_out_valid),
    .io_out_bits_addr  (_arb_io_out_bits_addr),
    .io_out_bits_op    (_arb_io_out_bits_op),
    .io_chosen         (_arb_io_chosen)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
  Queue1_MluStage1 stage2Input_q (	// src/main/scala/chisel3/util/Queue.scala:200:21
    .clock           (clock),
    .reset           (reset),
    .io_enq_ready    (_stage2Input_q_io_enq_ready),
    .io_enq_valid    (_arb_io_out_valid),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
    .io_enq_bits_rd  (_arb_io_out_bits_addr),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
    .io_enq_bits_op  (_arb_io_out_bits_op),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19
    .io_enq_bits_sel (4'h1 << _arb_io_chosen),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:67:19, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_deq_ready    (_stage3Input_q_io_enq_ready),	// src/main/scala/chisel3/util/Queue.scala:200:21
    .io_deq_valid    (_stage2Input_q_io_deq_valid),
    .io_deq_bits_rd  (_stage2Input_q_io_deq_bits_rd),
    .io_deq_bits_op  (_stage2Input_q_io_deq_bits_op),
    .io_deq_bits_sel (_stage2Input_q_io_deq_bits_sel)
  );	// src/main/scala/chisel3/util/Queue.scala:200:21
  Queue1_MluStage2 stage3Input_q (	// src/main/scala/chisel3/util/Queue.scala:200:21
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_stage3Input_q_io_enq_ready),
    .io_enq_valid     (_stage2Input_q_io_deq_valid),	// src/main/scala/chisel3/util/Queue.scala:200:21
    .io_enq_bits_rd   (_stage2Input_q_io_deq_bits_rd),	// src/main/scala/chisel3/util/Queue.scala:200:21
    .io_enq_bits_op   (_stage2Input_q_io_deq_bits_op),	// src/main/scala/chisel3/util/Queue.scala:200:21
    .io_enq_bits_prod
      ({{34{(_stage2Input_q_io_deq_bits_op == 3'h2 | rs2signed) & rs1[31]}}, rs1}
       * {{34{rs2signed & rs2[31]}}, rs2}),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:84:105, :85:105, :87:32, :88:{32,47}, :89:{28,34}, :90:{28,34}, :91:19, src/main/scala/chisel3/util/Queue.scala:200:21
    .io_deq_ready     (io_rd_ready),
    .io_deq_valid     (io_rd_valid),
    .io_deq_bits_rd   (io_rd_bits_addr),
    .io_deq_bits_op   (_stage3Input_q_io_deq_bits_op),
    .io_deq_bits_prod (_stage3Input_q_io_deq_bits_prod)
  );	// src/main/scala/chisel3/util/Queue.scala:200:21
  assign io_rd_bits_data =
    _stage3Input_q_io_deq_bits_op == 3'h0
      ? _stage3Input_q_io_deq_bits_prod[31:0]
      : _stage3Input_q_io_deq_bits_prod[63:32];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:55:7, :106:16, :107:13, :108:14, :109:14, src/main/scala/chisel3/util/OneHot.scala:58:35, src/main/scala/chisel3/util/Queue.scala:200:21
endmodule


// ----- 8< ----- FILE "verification/cover/layers-Mlu-Verification_Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_Mlu_Verification_Cover
`define layers_Mlu_Verification_Cover	// <stdin>:27:5
`endif // layers_Mlu_Verification_Cover	// <stdin>:27:5

// ----- 8< ----- FILE "verification/assume/layers-Mlu-Verification_Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_Mlu_Verification_Assume
`define layers_Mlu_Verification_Assume	// <stdin>:26:5
`endif // layers_Mlu_Verification_Assume	// <stdin>:26:5

// ----- 8< ----- FILE "verification/assert/layers-Mlu-Verification_Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_Mlu_Verification_Assert
`define layers_Mlu_Verification_Assert	// <stdin>:25:5
bind Mlu Mlu_Verification_Assert verification_Assert (
  .io_rs1_0_valid             (io_rs1_0_valid),
  .stage2Input_q_io_deq_valid (_stage2Input_q_io_deq_valid),
  ._GEN                       (_stage2Input_q_io_deq_bits_sel[0]),
  .io_rs2_0_valid             (io_rs2_0_valid),
  .io_rs1_1_valid             (io_rs1_1_valid),
  ._GEN_0                     (_stage2Input_q_io_deq_bits_sel[1]),
  .io_rs2_1_valid             (io_rs2_1_valid),
  .io_rs1_2_valid             (io_rs1_2_valid),
  ._GEN_1                     (_stage2Input_q_io_deq_bits_sel[2]),
  .io_rs2_2_valid             (io_rs2_2_valid),
  .io_rs1_3_valid             (io_rs1_3_valid),
  ._GEN_2                     (_stage2Input_q_io_deq_bits_sel[3]),
  .io_rs2_3_valid             (io_rs2_3_valid),
  .reset                      (reset),
  .clock                      (clock)
);
`endif // layers_Mlu_Verification_Assert	// <stdin>:25:5

// ----- 8< ----- FILE "verification/assert/Mlu_Verification_Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Mlu_Verification_Assert(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
  input io_rs1_0_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:39
        stage2Input_q_io_deq_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
        _GEN,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
        io_rs2_0_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:39
        io_rs1_1_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:39
        _GEN_0,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
        io_rs2_1_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:39
        io_rs1_2_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:39
        _GEN_1,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
        io_rs2_2_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:39
        io_rs1_3_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:39
        _GEN_2,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
        io_rs2_3_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:39
        reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
        clock	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
);

  `ifndef SYNTHESIS	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
    always @(posedge clock) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
      automatic logic _GEN_3 = stage2Input_q_io_deq_valid & _GEN;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
      automatic logic _GEN_4 = stage2Input_q_io_deq_valid & _GEN_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
      automatic logic _GEN_5 = stage2Input_q_io_deq_valid & _GEN_1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
      automatic logic _GEN_6 = stage2Input_q_io_deq_valid & _GEN_2;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:23
      if (~reset & _GEN_3 & ~io_rs1_0_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:{11,23,36,39}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
          $error("Assertion failed at Mlu.scala:122\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
      end
      if (~reset & _GEN_3 & ~io_rs2_0_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:{11,23}, :123:{11,36,39}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
          $error("Assertion failed at Mlu.scala:123\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
      end
      if (~reset & _GEN_4 & ~io_rs1_1_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:{11,23,36,39}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
          $error("Assertion failed at Mlu.scala:122\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
      end
      if (~reset & _GEN_4 & ~io_rs2_1_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:{11,23}, :123:{11,36,39}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
          $error("Assertion failed at Mlu.scala:123\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
      end
      if (~reset & _GEN_5 & ~io_rs1_2_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:{11,23,36,39}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
          $error("Assertion failed at Mlu.scala:122\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
      end
      if (~reset & _GEN_5 & ~io_rs2_2_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:{11,23}, :123:{11,36,39}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
          $error("Assertion failed at Mlu.scala:123\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
      end
      if (~reset & _GEN_6 & ~io_rs1_3_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:{11,23,36,39}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
          $error("Assertion failed at Mlu.scala:122\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:11
      end
      if (~reset & _GEN_6 & ~io_rs2_3_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:122:{11,23}, :123:{11,36,39}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
          $error("Assertion failed at Mlu.scala:123\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Mlu.scala:123:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

