// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Alu(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
  input         clock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
                reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
                io_req_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
  input  [4:0]  io_req_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
                io_req_bits_op,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
  input         io_rs1_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
  input  [31:0] io_rs1_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
  input         io_rs2_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
  input  [31:0] io_rs2_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
  output        io_rd_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
  output [4:0]  io_rd_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
  output [31:0] io_rd_bits_data	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
);

  reg               valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:79:22
  reg  [4:0]        addr;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:80:21
  reg  [4:0]        op;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:81:19
  wire              r2IsGreater = $signed(io_rs1_data) < $signed(io_rs2_data);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:100:32
  wire              r2IsGreaterU = io_rs1_data < io_rs2_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:101:26
  wire [31:0]       _io_rd_bits_data_T_19 = io_rs1_data ^ io_rs2_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:125:24
  wire [62:0]       _io_rd_bits_data_T_7 = {31'h0, io_rs1_data} << io_rs2_data[4:0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :128:25
  wire [31:0]       _GEN = {27'h0, io_rs2_data[4:0]};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :129:25
  wire [31:0]       _io_rd_bits_data_T_29 =
    {16'h0, io_rs1_data[31:16]} | {io_rs1_data[15:0], 16'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/Library.scala:106:42
  wire [31:0]       _io_rd_bits_data_T_39 =
    {8'h0, _io_rd_bits_data_T_29[31:8] & 24'hFF00FF}
    | {_io_rd_bits_data_T_29[23:0] & 24'hFF00FF, 8'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/Library.scala:106:42
  wire [31:0]       _io_rd_bits_data_T_49 =
    {4'h0, _io_rd_bits_data_T_39[31:4] & 28'hF0F0F0F}
    | {_io_rd_bits_data_T_39[27:0] & 28'hF0F0F0F, 4'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/Library.scala:106:42
  wire [31:0]       _io_rd_bits_data_T_59 =
    {2'h0, _io_rd_bits_data_T_49[31:2] & 30'h33333333}
    | {_io_rd_bits_data_T_49[29:0] & 30'h33333333, 2'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/Library.scala:106:42
  wire [31:0]       _io_rd_bits_data_T_69 =
    {1'h0, _io_rd_bits_data_T_59[31:1] & 31'h55555555}
    | {_io_rd_bits_data_T_59[30:0] & 31'h55555555, 1'h0};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/Library.scala:106:42, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
  wire [31:0]       _io_rd_bits_data_T_312 =
    io_rs2_data[0] ? {io_rs1_data[30:0], io_rs1_data[31]} : io_rs1_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :145:32
  wire [31:0]       _io_rd_bits_data_T_316 =
    io_rs2_data[1]
      ? {_io_rd_bits_data_T_312[29:0], _io_rd_bits_data_T_312[31:30]}
      : _io_rd_bits_data_T_312;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :145:32
  wire [31:0]       _io_rd_bits_data_T_320 =
    io_rs2_data[2]
      ? {_io_rd_bits_data_T_316[27:0], _io_rd_bits_data_T_316[31:28]}
      : _io_rd_bits_data_T_316;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :145:32
  wire [31:0]       _io_rd_bits_data_T_324 =
    io_rs2_data[3]
      ? {_io_rd_bits_data_T_320[23:0], _io_rd_bits_data_T_320[31:24]}
      : _io_rd_bits_data_T_320;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :145:32
  wire [31:0]       _io_rd_bits_data_T_337 =
    io_rs2_data[0] ? {io_rs1_data[0], io_rs1_data[31:1]} : io_rs1_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :138:27, :145:32, :146:33
  wire [31:0]       _io_rd_bits_data_T_341 =
    io_rs2_data[1]
      ? {_io_rd_bits_data_T_337[1:0], _io_rd_bits_data_T_337[31:2]}
      : _io_rd_bits_data_T_337;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :145:32, :146:33
  wire [31:0]       _io_rd_bits_data_T_345 =
    io_rs2_data[2]
      ? {_io_rd_bits_data_T_341[3:0], _io_rd_bits_data_T_341[31:4]}
      : _io_rd_bits_data_T_341;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :145:32, :146:33
  wire [31:0]       _io_rd_bits_data_T_349 =
    io_rs2_data[3]
      ? {_io_rd_bits_data_T_345[7:0], _io_rd_bits_data_T_345[31:8]}
      : _io_rd_bits_data_T_345;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:95:18, :145:32, :146:33
  wire [31:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {{16'h0, io_rs1_data[15:0]}},
     {{io_rs1_data[7:0], io_rs1_data[15:8], io_rs1_data[23:16], io_rs1_data[31:24]}},
     {{io_rs1_data[31:24] == 8'h0 ? 8'h0 : 8'hFF,
       io_rs1_data[23:16] == 8'h0 ? 8'h0 : 8'hFF,
       io_rs1_data[15:8] == 8'h0 ? 8'h0 : 8'hFF,
       io_rs1_data[7:0] == 8'h0 ? 8'h0 : 8'hFF}},
     {io_rs2_data[4]
        ? {_io_rd_bits_data_T_349[15:0], _io_rd_bits_data_T_349[31:16]}
        : _io_rd_bits_data_T_349},
     {io_rs2_data[4]
        ? {_io_rd_bits_data_T_324[15:0], _io_rd_bits_data_T_324[31:16]}
        : _io_rd_bits_data_T_324},
     {{{16{io_rs1_data[15]}}, io_rs1_data[15:0]}},
     {{{24{io_rs1_data[7]}}, io_rs1_data[7:0]}},
     {r2IsGreaterU ? io_rs1_data : io_rs2_data},
     {r2IsGreater ? io_rs1_data : io_rs2_data},
     {r2IsGreaterU ? io_rs2_data : io_rs1_data},
     {r2IsGreater ? io_rs2_data : io_rs1_data},
     {{26'h0,
       {1'h0,
        {1'h0,
         {1'h0,
          {1'h0, {1'h0, io_rs1_data[0]} + {1'h0, io_rs1_data[1]}}
            + {1'h0, {1'h0, io_rs1_data[2]} + {1'h0, io_rs1_data[3]}}}
           + {1'h0,
              {1'h0, {1'h0, io_rs1_data[4]} + {1'h0, io_rs1_data[5]}}
                + {1'h0, {1'h0, io_rs1_data[6]} + {1'h0, io_rs1_data[7]}}}}
          + {1'h0,
             {1'h0,
              {1'h0, {1'h0, io_rs1_data[8]} + {1'h0, io_rs1_data[9]}}
                + {1'h0, {1'h0, io_rs1_data[10]} + {1'h0, io_rs1_data[11]}}}
               + {1'h0,
                  {1'h0, {1'h0, io_rs1_data[12]} + {1'h0, io_rs1_data[13]}}
                    + {1'h0, {1'h0, io_rs1_data[14]} + {1'h0, io_rs1_data[15]}}}}}
         + {1'h0,
            {1'h0,
             {1'h0,
              {1'h0, {1'h0, io_rs1_data[16]} + {1'h0, io_rs1_data[17]}}
                + {1'h0, {1'h0, io_rs1_data[18]} + {1'h0, io_rs1_data[19]}}}
               + {1'h0,
                  {1'h0, {1'h0, io_rs1_data[20]} + {1'h0, io_rs1_data[21]}}
                    + {1'h0, {1'h0, io_rs1_data[22]} + {1'h0, io_rs1_data[23]}}}}
              + {1'h0,
                 {1'h0,
                  {1'h0, {1'h0, io_rs1_data[24]} + {1'h0, io_rs1_data[25]}}
                    + {1'h0, {1'h0, io_rs1_data[26]} + {1'h0, io_rs1_data[27]}}}
                   + {1'h0,
                      {1'h0, {1'h0, io_rs1_data[28]} + {1'h0, io_rs1_data[29]}}
                        + {1'h0, {1'h0, io_rs1_data[30]} + {1'h0, io_rs1_data[31]}}}}}}},
     {{26'h0,
       io_rs1_data[0]
         ? 6'h0
         : io_rs1_data[1]
             ? 6'h1
             : io_rs1_data[2]
                 ? 6'h2
                 : io_rs1_data[3]
                     ? 6'h3
                     : io_rs1_data[4]
                         ? 6'h4
                         : io_rs1_data[5]
                             ? 6'h5
                             : io_rs1_data[6]
                                 ? 6'h6
                                 : io_rs1_data[7]
                                     ? 6'h7
                                     : io_rs1_data[8]
                                         ? 6'h8
                                         : io_rs1_data[9]
                                             ? 6'h9
                                             : io_rs1_data[10]
                                                 ? 6'hA
                                                 : io_rs1_data[11]
                                                     ? 6'hB
                                                     : io_rs1_data[12]
                                                         ? 6'hC
                                                         : io_rs1_data[13]
                                                             ? 6'hD
                                                             : io_rs1_data[14]
                                                                 ? 6'hE
                                                                 : io_rs1_data[15]
                                                                     ? 6'hF
                                                                     : io_rs1_data[16]
                                                                         ? 6'h10
                                                                         : io_rs1_data[17]
                                                                             ? 6'h11
                                                                             : io_rs1_data[18]
                                                                                 ? 6'h12
                                                                                 : io_rs1_data[19]
                                                                                     ? 6'h13
                                                                                     : io_rs1_data[20]
                                                                                         ? 6'h14
                                                                                         : io_rs1_data[21]
                                                                                             ? 6'h15
                                                                                             : io_rs1_data[22]
                                                                                                 ? 6'h16
                                                                                                 : io_rs1_data[23]
                                                                                                     ? 6'h17
                                                                                                     : io_rs1_data[24]
                                                                                                         ? 6'h18
                                                                                                         : io_rs1_data[25]
                                                                                                             ? 6'h19
                                                                                                             : io_rs1_data[26]
                                                                                                                 ? 6'h1A
                                                                                                                 : io_rs1_data[27]
                                                                                                                     ? 6'h1B
                                                                                                                     : io_rs1_data[28]
                                                                                                                         ? 6'h1C
                                                                                                                         : io_rs1_data[29]
                                                                                                                             ? 6'h1D
                                                                                                                             : io_rs1_data[30]
                                                                                                                                 ? 6'h1E
                                                                                                                                 : io_rs1_data[31]
                                                                                                                                     ? 6'h1F
                                                                                                                                     : 6'h20}},
     {{26'h0,
       _io_rd_bits_data_T_69[0]
         ? 6'h0
         : _io_rd_bits_data_T_69[1]
             ? 6'h1
             : _io_rd_bits_data_T_69[2]
                 ? 6'h2
                 : _io_rd_bits_data_T_69[3]
                     ? 6'h3
                     : _io_rd_bits_data_T_69[4]
                         ? 6'h4
                         : _io_rd_bits_data_T_69[5]
                             ? 6'h5
                             : _io_rd_bits_data_T_69[6]
                                 ? 6'h6
                                 : _io_rd_bits_data_T_69[7]
                                     ? 6'h7
                                     : _io_rd_bits_data_T_69[8]
                                         ? 6'h8
                                         : _io_rd_bits_data_T_69[9]
                                             ? 6'h9
                                             : _io_rd_bits_data_T_69[10]
                                                 ? 6'hA
                                                 : _io_rd_bits_data_T_69[11]
                                                     ? 6'hB
                                                     : _io_rd_bits_data_T_69[12]
                                                         ? 6'hC
                                                         : _io_rd_bits_data_T_69[13]
                                                             ? 6'hD
                                                             : _io_rd_bits_data_T_69[14]
                                                                 ? 6'hE
                                                                 : _io_rd_bits_data_T_69[15]
                                                                     ? 6'hF
                                                                     : _io_rd_bits_data_T_69[16]
                                                                         ? 6'h10
                                                                         : _io_rd_bits_data_T_69[17]
                                                                             ? 6'h11
                                                                             : _io_rd_bits_data_T_69[18]
                                                                                 ? 6'h12
                                                                                 : _io_rd_bits_data_T_69[19]
                                                                                     ? 6'h13
                                                                                     : _io_rd_bits_data_T_69[20]
                                                                                         ? 6'h14
                                                                                         : _io_rd_bits_data_T_69[21]
                                                                                             ? 6'h15
                                                                                             : _io_rd_bits_data_T_69[22]
                                                                                                 ? 6'h16
                                                                                                 : _io_rd_bits_data_T_69[23]
                                                                                                     ? 6'h17
                                                                                                     : _io_rd_bits_data_T_69[24]
                                                                                                         ? 6'h18
                                                                                                         : _io_rd_bits_data_T_69[25]
                                                                                                             ? 6'h19
                                                                                                             : _io_rd_bits_data_T_69[26]
                                                                                                                 ? 6'h1A
                                                                                                                 : _io_rd_bits_data_T_69[27]
                                                                                                                     ? 6'h1B
                                                                                                                     : _io_rd_bits_data_T_69[28]
                                                                                                                         ? 6'h1C
                                                                                                                         : _io_rd_bits_data_T_69[29]
                                                                                                                             ? 6'h1D
                                                                                                                             : _io_rd_bits_data_T_69[30]
                                                                                                                                 ? 6'h1E
                                                                                                                                 : _io_rd_bits_data_T_69[31]
                                                                                                                                     ? 6'h1F
                                                                                                                                     : 6'h20}},
     {~_io_rd_bits_data_T_19},
     {io_rs1_data | ~io_rs2_data},
     {io_rs1_data & ~io_rs2_data},
     {io_rs2_data},
     {$signed($signed(io_rs1_data) >>> _GEN)},
     {io_rs1_data >> _GEN},
     {_io_rd_bits_data_T_7[31:0]},
     {io_rs1_data & io_rs2_data},
     {io_rs1_data | io_rs2_data},
     {_io_rd_bits_data_T_19},
     {{31'h0, r2IsGreaterU}},
     {{31'h0, r2IsGreater}},
     {io_rs1_data - io_rs2_data},
     {io_rs1_data + io_rs2_data}};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/common/Library.scala:106:42, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7, :95:18, :100:32, :101:26, :108:9, :114:16, :115:{10,12,21}, :120:41, :121:24, :122:24, :125:24, :126:24, :127:24, :128:{25,34}, :129:25, :130:33, :133:{24,26}, :134:24, :135:19, :138:27, :139:22, :140:22, :141:22, :142:22, :143:34, :145:32, :146:33, :148:22, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:48:45
  always @(posedge clock) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
    if (reset) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
      valid <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7, :79:22
      addr <= 5'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:80:21, :81:19
      op <= 5'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:81:19
    end
    else begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
      valid <= io_req_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:79:22
      if (io_req_valid) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:69:14
        addr <= io_req_bits_addr;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:80:21
        op <= io_req_bits_op;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:81:19
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
      `FIRRTL_BEFORE_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
      automatic logic [31:0] _RANDOM[0:0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
      `ifdef INIT_RANDOM_PROLOG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
        `INIT_RANDOM_PROLOG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
        valid = _RANDOM[/*Zero width*/ 1'b0][0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7, :79:22
        addr = _RANDOM[/*Zero width*/ 1'b0][5:1];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7, :79:22, :80:21
        op = _RANDOM[/*Zero width*/ 1'b0][10:6];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7, :79:22, :81:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
      `FIRRTL_AFTER_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rd_valid = valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7, :79:22
  assign io_rd_bits_addr = addr;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7, :80:21
  assign io_rd_bits_data = _GEN_0[op];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:68:7, :81:19, :120:41
endmodule


// ----- 8< ----- FILE "verification/cover/layers-Alu-Verification_Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_Alu_Verification_Cover
`define layers_Alu_Verification_Cover	// <stdin>:12:5
`endif // layers_Alu_Verification_Cover	// <stdin>:12:5

// ----- 8< ----- FILE "verification/assume/layers-Alu-Verification_Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_Alu_Verification_Assume
`define layers_Alu_Verification_Assume	// <stdin>:11:5
`endif // layers_Alu_Verification_Assume	// <stdin>:11:5

// ----- 8< ----- FILE "verification/assert/layers-Alu-Verification_Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_Alu_Verification_Assert
`define layers_Alu_Verification_Assert	// <stdin>:10:5
bind Alu Alu_Verification_Assert verification_Assert (
  .io_rs1_valid    (io_rs1_valid),
  ._GEN            (op == 5'hA),
  .valid           (valid),
  .io_rs2_valid    (io_rs2_valid),
  ._rs1Only_WIRE_5 (op == 5'h15),
  ._rs1Only_WIRE_4 (op == 5'h16),
  ._rs1Only_WIRE_7 (op == 5'h1A),
  ._rs1Only_WIRE_6 (op == 5'h19),
  ._rs1Only_WIRE_1 (op == 5'hF),
  ._rs1Only_WIRE_0 (op == 5'hE),
  ._rs1Only_WIRE_3 (op == 5'h1B),
  ._rs1Only_WIRE_2 (op == 5'h10),
  .reset           (reset),
  .clock           (clock)
);
`endif // layers_Alu_Verification_Assert	// <stdin>:10:5

// ----- 8< ----- FILE "verification/assert/Alu_Verification_Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Alu_Verification_Assert(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:160:9
  input io_rs1_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:21
        _GEN,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:38
        valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:18
        io_rs2_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:160:21
        _rs1Only_WIRE_5,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27
        _rs1Only_WIRE_4,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27
        _rs1Only_WIRE_7,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27
        _rs1Only_WIRE_6,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27
        _rs1Only_WIRE_1,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27
        _rs1Only_WIRE_0,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27
        _rs1Only_WIRE_3,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27
        _rs1Only_WIRE_2,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27
        reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:9
        clock	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:9
);

  `ifndef SYNTHESIS	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:9
    always @(posedge clock) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:9
      if (~reset & valid & ~io_rs1_valid & ~_GEN) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:{9,18,21,35,38}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:9
          $error("Assertion failed at Alu.scala:159\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:9
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:9
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:159:9
      end
      if (~reset & valid & ~io_rs2_valid
          & {_rs1Only_WIRE_7,
             _rs1Only_WIRE_6,
             _rs1Only_WIRE_5,
             _rs1Only_WIRE_4,
             _rs1Only_WIRE_3,
             _rs1Only_WIRE_2,
             _rs1Only_WIRE_1,
             _rs1Only_WIRE_0} == 8'h0) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:154:27, :159:9, :160:{9,18,21,35}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:160:9
          $error("Assertion failed at Alu.scala:160\n");	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:160:9
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:160:9
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/scalar/Alu.scala:160:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

